# Use official OpenJDK 17 as a base image
FROM openjdk:17-alpine

# Set the working directory inside the container
WORKDIR /app

# Copy the Maven wrapper script and project object model file
COPY mvnw .
COPY .mvn .mvn
COPY pom.xml .


# Copy the JAR file generated by Maven into the container
COPY target/EbookManagementSytem-0.0.1-SNAPSHOT.jar EbookManagementSytem.jar

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["java", "-jar", "EbookManagementSytem.jar"]
